CREATE TABLE IF NOT EXISTS users (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(255) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	user_id BIGINT NOT NULL,
	product_name VARCHAR(255) NOT NULL,
	quantity INT NOT NULL,
	price DECIMAL(12,2) NOT NULL,
	created_at TIMESTAMP NOT NULL,
	CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id)
); 