name: Backend CI

on:
  push:
    paths:
      - 'oms-api/**'
  pull_request:
    paths:
      - 'oms-api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Build and Test
        working-directory: oms-api
        run: ./mvnw -B -q -DskipITs=true test 